name: "Pull Request Docs Check HTML"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
    - uses: actions/upload-artifact@v3 # https://github.com/actions/upload-artifact
      with:
        name: DocumentationHTML
        path: _build/html/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
